// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package mapsdb

import (
	"time"
)

type GalleryImage struct {
	ID            string
	CampaignID    string
	UploadedBy    *string
	Name          string
	ContentType   string
	Width         int32
	Height        int32
	ByteSize      int32
	CreatedAt     time.Time
	Generated     bool
	ParentImageID *string
	GeneratedKind string
	CopyOfImageID *string
}

type GeneratedDungeon struct {
	MapID            string
	GeneratorVersion int32
	Seed             int64
	Width            int32
	Height           int32
	Options          []byte
	Cells            []byte
	Rooms            []byte
	CreatedAt        time.Time
	ImageID          *string
}

type ImageRequest struct {
	ID              string
	CampaignID      string
	RequestedBy     *string
	IdempotencyKey  string
	Kind            string
	Prompt          string
	Style           string
	AspectRatio     string
	Model           string
	ReferenceIds    []string
	CharacterIds    []string
	SourceImageID   *string
	Number          int32
	QuotaMonth      string
	Status          string
	Reason          string
	Refunded        bool
	ImageID         *string
	CreatedAt       time.Time
	SentAt          *time.Time
	FinishedAt      *time.Time
	MapID           *string
	MapImageID      *string
	MapGridColumns  *int32
	MapGridFactor   *int32
	MapWidth        *int32
	MapHeight       *int32
	MapPlanHash     *string
	PadX0           *float64
	PadY0           *float64
	PadX1           *float64
	PadY1           *float64
	UsedMapImageID  *string
	ImageName       string
	IdempotencyHash *string
}

type Map struct {
	ID             string
	CampaignID     string
	Name           string
	ImageID        string
	RevealedAt     *time.Time
	Revision       int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	GridColumns    *int32
	FogEnabled     bool
	BaseLight      string
	GroupVision    bool
	LayersRevision int32
	LightRevision  int32
	VisionEpoch    int32
	FogOnFirstGrid bool
	GridFactor     int32
	CreateKey      *string
	CreateHash     *string
}

type MapCreatureToken struct {
	MapID      string
	CreatureID string
	XBp        int32
	YBp        int32
	UpdatedAt  time.Time
}

type MapLayer struct {
	MapID            string
	DifficultTerrain []byte
	Walls            []byte
	Cover            []byte
	Light            []byte
	UpdatedAt        time.Time
	Doors            []byte
}

type MapPoint struct {
	ID                       string
	MapID                    string
	Kind                     string
	Name                     string
	Description              string
	XBp                      int32
	YBp                      int32
	TargetMapID              *string
	RevealedAt               *time.Time
	CreatedAt                time.Time
	UpdatedAt                time.Time
	Hooks                    string
	ShowDc                   bool
	Trap                     []byte
	TrapState                *string
	TrapTriggeredAt          *time.Time
	TreasureValuePo          *int32
	TreasureFoundAt          *time.Time
	TreasureSessionID        *string
	TreasureConvertedAwardID *string
	LightPreset              *string
	LightBrightFt            *int32
	LightDimFt               *int32
	Stairs                   *string
	CreateKey                *string
	CreateHash               *string
}

type MapPointReveal struct {
	PointID     string
	CharacterID string
	How         string
	At          time.Time
}

type MapToken struct {
	MapID        string
	CharacterID  string
	XBp          int32
	YBp          int32
	Hidden       bool
	UpdatedAt    time.Time
	CarriedLight *string
}

type MapTreasureFinder struct {
	PointID     string
	CharacterID string
}

type SceneAction struct {
	ID          string
	PointID     string
	Position    int32
	Key         string
	Name        string
	Dc          *int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	MaxAttempts int32
	CreateKey   *string
	CreateHash  *string
}

type SceneClue struct {
	ID         string
	PointID    string
	Position   int32
	Text       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	CreateKey  *string
	CreateHash *string
}
