// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package playdb

import (
	"time"
)

type BattleEncounter struct {
	MapPointID string
	CampaignID string
	MapID      string
	Encounter  []byte
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Combatant struct {
	ID                 string
	EncounterID        string
	CharacterID        string
	UserID             *string
	Label              string
	Kind               string
	Hidden             bool
	Initiative         *int32
	InitiativeBonus    int32
	InitiativeFace     *int32
	TieOrdered         bool
	OrderIndex         int32
	GridCol            *int32
	GridRow            *int32
	SpeedFt            int32
	MovementUsedFt     int32
	Dashed             bool
	ActionUsed         bool
	BonusActionUsed    bool
	ReactionUsed       bool
	HpCurrent          *int32
	HpMax              *int32
	HpTemp             *int32
	Defeated           bool
	DeathSuccesses     int32
	DeathFailures      int32
	Conditions         []string
	ConcentrationSpell *string
	CreatedAt          time.Time
	AttacksMade        int32
	AcBonus            int32
	DeathSaveRolled    bool
	XpValue            int32
	TurnState          string
	MovementUsedDft    int32
	LastMoveDft        int32
	Side               string
	Size               string
	SpeedFlyFt         int32
	JumpLongDft        int32
	JumpHighDft        int32
	CoverMark          string
	Disengaged         bool
	CreatureID         *string
	MonsterKey         *string
	SummonAttack       *string
	SummonGroupID      *string
	Dismissed          bool
	ActionSurged       bool
	SpellCast          bool
	BonusSpellCast     bool
	ActionAttackKey    *string
	BonusAttacksLeft   int32
	MonsterState       []byte
}

type Encounter struct {
	ID                 string
	GameSessionID      string
	MapID              *string
	MapPointID         *string
	Name               string
	Status             string
	Round              int32
	CurrentCombatantID *string
	GridColumns        int32
	GridRows           int32
	Revision           int32
	CreatedAt          time.Time
	StartedAt          *time.Time
	EndedAt            *time.Time
	Mode               string
}

type GameSession struct {
	ID               string
	CampaignID       string
	SessionNumber    int32
	StartedAt        time.Time
	EndedAt          *time.Time
	CurrentMapID     *string
	ShownImageID     *string
	ShownImageKeep   bool
	OpenScenePointID *string
	CreateKey        *string
	CreateHash       *string
}

type OpportunityOffer struct {
	ID              string
	EncounterID     string
	MoveID          string
	MoverID         string
	ReactorID       string
	LeftCol         *int32
	LeftRow         *int32
	State           string
	AttackPendingID *string
	CreatedAt       time.Time
	AnsweredAt      *time.Time
}

type PendingDamage struct {
	ID               string
	EncounterID      string
	AttackerID       *string
	TargetID         string
	AttackKey        string
	Status           string
	Critical         bool
	DiceCount        int32
	DiceSides        int32
	DiceBonus        int32
	DamageType       string
	Faces            []int32
	Physical         bool
	Amount           *int32
	CreatedAt        time.Time
	ResolvedAt       *time.Time
	CastID           *string
	Healing          bool
	Half             bool
	AppliedAmount    *int32
	AttackTotal      *int32
	RollTotal        *int32
	AttackArmorClass *int32
	TrapPointID      *string
	CriticalMax      int32
	CriticalMaxRule  bool
	Taken            *int32
}

type Puzzle struct {
	ID           string
	CampaignID   string
	Kind         string
	Name         string
	Config       []byte
	Solution     []byte
	Seed         int64
	Start        []byte
	MinimumMoves *int32
	Clue         string
	Hints        []byte
	SolveAction  string
	SolveTarget  []byte
	ArchivedAt   *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	HintSkill    *string
	HintDc       *int32
	Parts        []byte
	OnWrong      []byte
	CreateKey    *string
	CreateHash   *string
}

type PuzzleHintTry struct {
	ID             string
	RunID          string
	UserID         *string
	CharacterID    *string
	IdempotencyKey string
	HintIndex      int32
	Passed         bool
	GrantedCount   *int32
	D20            int32
	Modifier       int32
	Total          int32
	Physical       bool
	CreatedAt      time.Time
}

type PuzzleMove struct {
	ID             string
	RunID          string
	Seq            int32
	UserID         *string
	CharacterID    *string
	IdempotencyKey string
	Move           []byte
	Revision       int32
	Solved         bool
	CreatedAt      time.Time
	Wrong          bool
}

type PuzzleRun struct {
	ID                   string
	GameSessionID        string
	PuzzleID             string
	Seed                 int64
	Start                []byte
	State                []byte
	ReleasedHints        int32
	ShownAt              *time.Time
	ClosedAt             *time.Time
	SolvedAt             *time.Time
	SolvedByCharacterID  *string
	SolveOutcome         *string
	LastMoverCharacterID *string
	LastMove             []byte
	LastMovedAt          *time.Time
	MovesMade            int32
	Revision             int32
	CreatedAt            time.Time
	UpdatedAt            time.Time
	SolveMessage         *string
	Plays                int32
	PlayStartedAt        *time.Time
	RoundStartSeq        int32
	RoundStartedAt       *time.Time
}

type StageNpc struct {
	ID            string
	GameSessionID string
	CharacterID   string
	Position      int32
	Speaking      bool
	CreatedAt     time.Time
}

type TrapDamage struct {
	ID            string
	GameSessionID string
	TrapPointID   string
	FireID        string
	CharacterID   string
	Status        string
	Critical      bool
	DiceCount     int32
	DiceSides     int32
	DiceBonus     int32
	DamageType    string
	Faces         []int32
	RollTotal     int32
	Half          bool
	Amount        int32
	AppliedAmount *int32
	CreatedAt     time.Time
	ResolvedAt    *time.Time
	CriticalMax   int32
	SettleKey     *string
	SettleHash    *string
}
