// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package campaignsdb

import (
	"context"
	"time"
)

const activatePendingMember = `-- name: ActivatePendingMember :execrows
UPDATE campaign_members
SET status = 'active', pending_expires_at = NULL
WHERE campaign_id = $1 AND user_id = $2 AND status = 'pending'
`

type ActivatePendingMemberParams struct {
	CampaignID string
	UserID     string
}

// The master approved the pending member's character (RN-15): the
// membership becomes an ordinary one. An active membership matches no row
// and stays as it is.
func (q *Queries) ActivatePendingMember(ctx context.Context, arg ActivatePendingMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, activatePendingMember, arg.CampaignID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearPendingExpiry = `-- name: ClearPendingExpiry :execrows
UPDATE campaign_members
SET pending_expires_at = NULL
WHERE campaign_id = $1 AND user_id = $2 AND status = 'pending'
  AND (pending_expires_at IS NULL OR pending_expires_at > $3::timestamptz)
`

type ClearPendingExpiryParams struct {
	CampaignID string
	UserID     string
	Now        time.Time
}

// A pending member created their character (RN-15): the master decides on
// it now, so the 30-day deadline for a pending member without a character
// no longer applies. A deadline that has already passed stays: that member
// is no member any more (GetMembership).
func (q *Queries) ClearPendingExpiry(ctx context.Context, arg ClearPendingExpiryParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearPendingExpiry, arg.CampaignID, arg.UserID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countMasteredCampaigns = `-- name: CountMasteredCampaigns :one
SELECT count(*)::INT4 FROM campaign_members
WHERE user_id = $1 AND role = 'master'
`

// How many campaigns the user is master of, for the cap on creating (RN-30).
// The index on campaign_members (user_id) finds the user's few rows.
func (q *Queries) CountMasteredCampaigns(ctx context.Context, userID string) (int32, error) {
	row := q.db.QueryRow(ctx, countMasteredCampaigns, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteExpiredPendingMember = `-- name: DeleteExpiredPendingMember :execrows
DELETE FROM campaign_members
WHERE campaign_id = $1 AND user_id = $2 AND status = 'pending'
  AND pending_expires_at IS NOT NULL AND pending_expires_at <= $3::timestamptz
`

type DeleteExpiredPendingMemberParams struct {
	CampaignID string
	UserID     string
	Now        time.Time
}

// A pending member who never created a character and whose deadline has
// passed, but whom the TTL job has not deleted yet, joins again with a new
// invite: the stale row goes first, so the new one does not clash with it.
func (q *Queries) DeleteExpiredPendingMember(ctx context.Context, arg DeleteExpiredPendingMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredPendingMember, arg.CampaignID, arg.UserID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePendingMember = `-- name: DeletePendingMember :execrows
DELETE FROM campaign_members
WHERE campaign_id = $1 AND user_id = $2 AND status = 'pending'
`

type DeletePendingMemberParams struct {
	CampaignID string
	UserID     string
}

// The master rejected the pending member's character (RN-15): the pending
// membership goes with it. status = 'pending' in the WHERE clause means an
// active membership is never deleted here.
func (q *Queries) DeletePendingMember(ctx context.Context, arg DeletePendingMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePendingMember, arg.CampaignID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePendingMemberWithoutCharacter = `-- name: DeletePendingMemberWithoutCharacter :execrows
DELETE FROM campaign_members
WHERE campaign_id = $1 AND user_id = $2 AND status = 'pending' AND pending_expires_at IS NOT NULL
`

type DeletePendingMemberWithoutCharacterParams struct {
	CampaignID string
	UserID     string
}

// The master removed a pending member who has no character. The WHERE
// clause matches only that: an active member, or a pending member whose
// character waits for approval (pending_expires_at is NULL), is never
// deleted here; that one goes through RejectCharacter.
func (q *Queries) DeletePendingMemberWithoutCharacter(ctx context.Context, arg DeletePendingMemberWithoutCharacterParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePendingMemberWithoutCharacter, arg.CampaignID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, name, xp_mode, created_by, created_at, dice_mode, xp_mode_changed_at, create_key, create_hash FROM campaigns WHERE id = $1
`

func (q *Queries) GetCampaign(ctx context.Context, id string) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaign, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.XpMode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DiceMode,
		&i.XpModeChangedAt,
		&i.CreateKey,
		&i.CreateHash,
	)
	return i, err
}

const getCampaignByCreateKey = `-- name: GetCampaignByCreateKey :one
SELECT id, name, xp_mode, created_by, created_at, dice_mode, xp_mode_changed_at, create_key, create_hash FROM campaigns WHERE create_key = $1
`

// The campaign a CreateCampaign with this idempotency key made, if any. The key carries the
// user's ID, so it is unique for the user.
func (q *Queries) GetCampaignByCreateKey(ctx context.Context, createKey *string) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByCreateKey, createKey)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.XpMode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DiceMode,
		&i.XpModeChangedAt,
		&i.CreateKey,
		&i.CreateHash,
	)
	return i, err
}

const getCampaignDocument = `-- name: GetCampaignDocument :one
SELECT campaign_id, body, revision, updated_at, updated_by FROM campaign_documents WHERE campaign_id = $1
`

// The campaign's document (MR-018). No row means it was never saved: an
// empty document at revision 0.
func (q *Queries) GetCampaignDocument(ctx context.Context, campaignID string) (CampaignDocument, error) {
	row := q.db.QueryRow(ctx, getCampaignDocument, campaignID)
	var i CampaignDocument
	err := row.Scan(
		&i.CampaignID,
		&i.Body,
		&i.Revision,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getCampaignForUpdate = `-- name: GetCampaignForUpdate :one
SELECT id, name, xp_mode, created_by, created_at, dice_mode, xp_mode_changed_at, create_key, create_hash FROM campaigns WHERE id = $1 FOR UPDATE
`

// The campaign, locked until the transaction ends: a change of the XP mode reads
// the awards and writes the mode as one step.
func (q *Queries) GetCampaignForUpdate(ctx context.Context, id string) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignForUpdate, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.XpMode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DiceMode,
		&i.XpModeChangedAt,
		&i.CreateKey,
		&i.CreateHash,
	)
	return i, err
}

const getInviteByTokenHashForUpdate = `-- name: GetInviteByTokenHashForUpdate :one
SELECT id, campaign_id, token_hash, created_by, max_uses, use_count, created_at, expires_at, revoked_at, requires_approval FROM campaign_invites WHERE token_hash = $1 FOR UPDATE
`

// FOR UPDATE locks the invite until the transaction ends. A second
// AcceptInvite for the same invite waits here, instead of both reading the
// same use_count, and then sees the first one's result.
func (q *Queries) GetInviteByTokenHashForUpdate(ctx context.Context, tokenHash []byte) (CampaignInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenHashForUpdate, tokenHash)
	var i CampaignInvite
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.TokenHash,
		&i.CreatedBy,
		&i.MaxUses,
		&i.UseCount,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RequiresApproval,
	)
	return i, err
}

const getMemberDicePreference = `-- name: GetMemberDicePreference :one
SELECT dice_preference FROM campaign_members
WHERE campaign_id = $1 AND user_id = $2 AND status = 'active'
`

type GetMemberDicePreferenceParams struct {
	CampaignID string
	UserID     string
}

func (q *Queries) GetMemberDicePreference(ctx context.Context, arg GetMemberDicePreferenceParams) (string, error) {
	row := q.db.QueryRow(ctx, getMemberDicePreference, arg.CampaignID, arg.UserID)
	var dice_preference string
	err := row.Scan(&dice_preference)
	return dice_preference, err
}

const getMembership = `-- name: GetMembership :one
SELECT role, status FROM campaign_members
WHERE campaign_id = $1 AND user_id = $2
  AND (pending_expires_at IS NULL OR pending_expires_at > $3::timestamptz)
`

type GetMembershipParams struct {
	CampaignID string
	UserID     string
	Now        time.Time
}

type GetMembershipRow struct {
	Role   string
	Status string
}

// The query behind every authorization check (package authz): one read of
// the primary key. A pending member past the 30-day deadline (RN-15) is
// no member, even before the daily TTL job deletes the row.
func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (GetMembershipRow, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.CampaignID, arg.UserID, arg.Now)
	var i GetMembershipRow
	err := row.Scan(&i.Role, &i.Status)
	return i, err
}

const getTableRules = `-- name: GetTableRules :one
SELECT campaign_id, hit_points_rule, ability_standard_array, ability_point_buy, ability_roll_4d6, ability_typed, critical_rule, death_saves, combat_starts_with_map, fog_on_new_maps, house_rules, updated_at FROM campaign_table_rules WHERE campaign_id = $1
`

// The table's rules (RN-24). No row means the defaults.
func (q *Queries) GetTableRules(ctx context.Context, campaignID string) (CampaignTableRule, error) {
	row := q.db.QueryRow(ctx, getTableRules, campaignID)
	var i CampaignTableRule
	err := row.Scan(
		&i.CampaignID,
		&i.HitPointsRule,
		&i.AbilityStandardArray,
		&i.AbilityPointBuy,
		&i.AbilityRoll4d6,
		&i.AbilityTyped,
		&i.CriticalRule,
		&i.DeathSaves,
		&i.CombatStartsWithMap,
		&i.FogOnNewMaps,
		&i.HouseRules,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementInviteUses = `-- name: IncrementInviteUses :execrows
UPDATE campaign_invites
SET use_count = use_count + 1
WHERE id = $1 AND use_count < max_uses AND revoked_at IS NULL AND expires_at > $2
`

type IncrementInviteUsesParams struct {
	ID  string
	Now time.Time
}

// The WHERE clause repeats the rules, so an invite is never used more than
// max_uses times, after it expires or after it is revoked, even if the Go
// checks before it had a bug.
func (q *Queries) IncrementInviteUses(ctx context.Context, arg IncrementInviteUsesParams) (int64, error) {
	result, err := q.db.Exec(ctx, incrementInviteUses, arg.ID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertCampaign = `-- name: InsertCampaign :one
INSERT INTO campaigns (name, xp_mode, created_by, create_key, create_hash)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (create_key) WHERE create_key IS NOT NULL DO NOTHING
RETURNING id, name, xp_mode, created_by, created_at, dice_mode, xp_mode_changed_at, create_key, create_hash
`

type InsertCampaignParams struct {
	Name       string
	XpMode     string
	CreatedBy  string
	CreateKey  *string
	CreateHash *string
}

// create_key and create_hash are the idempotency key of CreateCampaign and the hash of its
// request (NULL when the call sent no key). Two calls with the same key at once make one
// campaign: the loser gets no row, and reads the winner's (GetCampaignByCreateKey).
func (q *Queries) InsertCampaign(ctx context.Context, arg InsertCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, insertCampaign,
		arg.Name,
		arg.XpMode,
		arg.CreatedBy,
		arg.CreateKey,
		arg.CreateHash,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.XpMode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DiceMode,
		&i.XpModeChangedAt,
		&i.CreateKey,
		&i.CreateHash,
	)
	return i, err
}

const insertCampaignDocument = `-- name: InsertCampaignDocument :one
INSERT INTO campaign_documents (campaign_id, body, revision, updated_at, updated_by)
VALUES ($1, $2, 1, $3, $4)
ON CONFLICT (campaign_id) DO NOTHING
RETURNING campaign_id, body, revision, updated_at, updated_by
`

type InsertCampaignDocumentParams struct {
	CampaignID string
	Body       string
	UpdatedAt  time.Time
	UpdatedBy  *string
}

// The first save of a campaign's document, at revision 1. When someone else
// saved first, ON CONFLICT DO NOTHING returns no row: the caller's revision
// (0) is stale.
func (q *Queries) InsertCampaignDocument(ctx context.Context, arg InsertCampaignDocumentParams) (CampaignDocument, error) {
	row := q.db.QueryRow(ctx, insertCampaignDocument,
		arg.CampaignID,
		arg.Body,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	var i CampaignDocument
	err := row.Scan(
		&i.CampaignID,
		&i.Body,
		&i.Revision,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const insertInvite = `-- name: InsertInvite :one
INSERT INTO campaign_invites
    (campaign_id, token_hash, created_by, max_uses, created_at, expires_at, requires_approval)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, campaign_id, token_hash, created_by, max_uses, use_count, created_at, expires_at, revoked_at, requires_approval
`

type InsertInviteParams struct {
	CampaignID       string
	TokenHash        []byte
	CreatedBy        string
	MaxUses          int32
	CreatedAt        time.Time
	ExpiresAt        time.Time
	RequiresApproval bool
}

func (q *Queries) InsertInvite(ctx context.Context, arg InsertInviteParams) (CampaignInvite, error) {
	row := q.db.QueryRow(ctx, insertInvite,
		arg.CampaignID,
		arg.TokenHash,
		arg.CreatedBy,
		arg.MaxUses,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.RequiresApproval,
	)
	var i CampaignInvite
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.TokenHash,
		&i.CreatedBy,
		&i.MaxUses,
		&i.UseCount,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RequiresApproval,
	)
	return i, err
}

const insertMember = `-- name: InsertMember :one
INSERT INTO campaign_members (campaign_id, user_id, role, status, pending_expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING campaign_id, user_id, role, joined_at, status, pending_expires_at, dice_preference
`

type InsertMemberParams struct {
	CampaignID       string
	UserID           string
	Role             string
	Status           string
	PendingExpiresAt *time.Time
}

// pending_expires_at is NULL, except for a pending member, who has no
// character yet: joined time + 30 days (RN-15, migration 00034).
func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) (CampaignMember, error) {
	row := q.db.QueryRow(ctx, insertMember,
		arg.CampaignID,
		arg.UserID,
		arg.Role,
		arg.Status,
		arg.PendingExpiresAt,
	)
	var i CampaignMember
	err := row.Scan(
		&i.CampaignID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.Status,
		&i.PendingExpiresAt,
		&i.DicePreference,
	)
	return i, err
}

const listCampaignsOfUser = `-- name: ListCampaignsOfUser :many
SELECT c.id, c.name, c.xp_mode, c.created_by, c.created_at, c.dice_mode, c.xp_mode_changed_at, c.create_key, c.create_hash, m.role, m.status
FROM campaign_members AS m
JOIN campaigns AS c ON c.id = m.campaign_id
WHERE m.user_id = $1
ORDER BY c.created_at DESC, c.id
`

type ListCampaignsOfUserRow struct {
	Campaign Campaign
	Role     string
	Status   string
}

// Newest first. The index on campaign_members (user_id) finds the rows.
// Pending memberships (RN-15) come too: the handler shows only the name.
func (q *Queries) ListCampaignsOfUser(ctx context.Context, userID string) ([]ListCampaignsOfUserRow, error) {
	rows, err := q.db.Query(ctx, listCampaignsOfUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampaignsOfUserRow
	for rows.Next() {
		var i ListCampaignsOfUserRow
		if err := rows.Scan(
			&i.Campaign.ID,
			&i.Campaign.Name,
			&i.Campaign.XpMode,
			&i.Campaign.CreatedBy,
			&i.Campaign.CreatedAt,
			&i.Campaign.DiceMode,
			&i.Campaign.XpModeChangedAt,
			&i.Campaign.CreateKey,
			&i.Campaign.CreateHash,
			&i.Role,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvites = `-- name: ListInvites :many
SELECT id, campaign_id, token_hash, created_by, max_uses, use_count, created_at, expires_at, revoked_at, requires_approval FROM campaign_invites
WHERE campaign_id = $1
ORDER BY created_at DESC, id
`

// Newest first. Invites that expired more than 30 days ago are gone (TTL).
func (q *Queries) ListInvites(ctx context.Context, campaignID string) ([]CampaignInvite, error) {
	rows, err := q.db.Query(ctx, listInvites, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CampaignInvite
	for rows.Next() {
		var i CampaignInvite
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.TokenHash,
			&i.CreatedBy,
			&i.MaxUses,
			&i.UseCount,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RequiresApproval,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT campaign_id, user_id, role, joined_at, status, pending_expires_at, dice_preference FROM campaign_members
WHERE campaign_id = $1 AND status = 'active'
ORDER BY role = 'master' DESC, joined_at, user_id
`

// The master first, then the players in the order they joined. Pending
// members (RN-15) are not members yet, so they are left out.
func (q *Queries) ListMembers(ctx context.Context, campaignID string) ([]CampaignMember, error) {
	rows, err := q.db.Query(ctx, listMembers, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CampaignMember
	for rows.Next() {
		var i CampaignMember
		if err := rows.Scan(
			&i.CampaignID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Status,
			&i.PendingExpiresAt,
			&i.DicePreference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingMembersWithoutCharacter = `-- name: ListPendingMembersWithoutCharacter :many
SELECT user_id, joined_at, pending_expires_at FROM campaign_members
WHERE campaign_id = $1 AND status = 'pending' AND pending_expires_at > $2::timestamptz
ORDER BY joined_at, user_id
`

type ListPendingMembersWithoutCharacterParams struct {
	CampaignID string
	Now        time.Time
}

type ListPendingMembersWithoutCharacterRow struct {
	UserID           string
	JoinedAt         time.Time
	PendingExpiresAt *time.Time
}

// The pending members who have not created a character, in the order they
// joined. pending_expires_at is set exactly for them (migration 00034).
func (q *Queries) ListPendingMembersWithoutCharacter(ctx context.Context, arg ListPendingMembersWithoutCharacterParams) ([]ListPendingMembersWithoutCharacterRow, error) {
	rows, err := q.db.Query(ctx, listPendingMembersWithoutCharacter, arg.CampaignID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingMembersWithoutCharacterRow
	for rows.Next() {
		var i ListPendingMembersWithoutCharacterRow
		if err := rows.Scan(&i.UserID, &i.JoinedAt, &i.PendingExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvite = `-- name: RevokeInvite :one
UPDATE campaign_invites
SET revoked_at = COALESCE(revoked_at, $3)
WHERE campaign_id = $1 AND id = $2
RETURNING id, campaign_id, token_hash, created_by, max_uses, use_count, created_at, expires_at, revoked_at, requires_approval
`

type RevokeInviteParams struct {
	CampaignID string
	ID         string
	Now        *time.Time
}

// Revoking twice keeps the first revoked_at, so RevokeInvite is idempotent.
// An invite of another campaign matches no row, which reads as "not found".
func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) (CampaignInvite, error) {
	row := q.db.QueryRow(ctx, revokeInvite, arg.CampaignID, arg.ID, arg.Now)
	var i CampaignInvite
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.TokenHash,
		&i.CreatedBy,
		&i.MaxUses,
		&i.UseCount,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RequiresApproval,
	)
	return i, err
}

const setCampaignDiceMode = `-- name: SetCampaignDiceMode :one
UPDATE campaigns SET dice_mode = $2 WHERE id = $1 RETURNING dice_mode
`

type SetCampaignDiceModeParams struct {
	ID       string
	DiceMode string
}

// The master changed how the campaign rolls dice (RN-18).
func (q *Queries) SetCampaignDiceMode(ctx context.Context, arg SetCampaignDiceModeParams) (string, error) {
	row := q.db.QueryRow(ctx, setCampaignDiceMode, arg.ID, arg.DiceMode)
	var dice_mode string
	err := row.Scan(&dice_mode)
	return dice_mode, err
}

const setCampaignXPMode = `-- name: SetCampaignXPMode :one
UPDATE campaigns SET xp_mode = $2, xp_mode_changed_at = $3::TIMESTAMPTZ WHERE id = $1 RETURNING xp_mode, xp_mode_changed_at
`

type SetCampaignXPModeParams struct {
	ID     string
	XpMode string
	Now    time.Time
}

type SetCampaignXPModeRow struct {
	XpMode          string
	XpModeChangedAt *time.Time
}

// The master changed how the campaign levels (RN-09).
func (q *Queries) SetCampaignXPMode(ctx context.Context, arg SetCampaignXPModeParams) (SetCampaignXPModeRow, error) {
	row := q.db.QueryRow(ctx, setCampaignXPMode, arg.ID, arg.XpMode, arg.Now)
	var i SetCampaignXPModeRow
	err := row.Scan(&i.XpMode, &i.XpModeChangedAt)
	return i, err
}

const setMemberDicePreference = `-- name: SetMemberDicePreference :one
UPDATE campaign_members SET dice_preference = $3
WHERE campaign_id = $1 AND user_id = $2 AND status = 'active'
RETURNING dice_preference
`

type SetMemberDicePreferenceParams struct {
	CampaignID     string
	UserID         string
	DicePreference string
}

// An active member chose how they roll (RN-18). Pending members are not
// members yet, so no row matches them.
func (q *Queries) SetMemberDicePreference(ctx context.Context, arg SetMemberDicePreferenceParams) (string, error) {
	row := q.db.QueryRow(ctx, setMemberDicePreference, arg.CampaignID, arg.UserID, arg.DicePreference)
	var dice_preference string
	err := row.Scan(&dice_preference)
	return dice_preference, err
}

const updateCampaignDocument = `-- name: UpdateCampaignDocument :one
UPDATE campaign_documents
SET body = $1,
    revision = revision + 1,
    updated_at = $2,
    updated_by = $3
WHERE campaign_id = $4 AND revision = $5
RETURNING campaign_id, body, revision, updated_at, updated_by
`

type UpdateCampaignDocumentParams struct {
	Body             string
	UpdatedAt        time.Time
	UpdatedBy        *string
	CampaignID       string
	ExpectedRevision int32
}

// Every later save: it replaces the body only while the stored revision is
// the one the caller read (compare-and-swap), and raises it by one. No row
// means the revision is stale.
func (q *Queries) UpdateCampaignDocument(ctx context.Context, arg UpdateCampaignDocumentParams) (CampaignDocument, error) {
	row := q.db.QueryRow(ctx, updateCampaignDocument,
		arg.Body,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.CampaignID,
		arg.ExpectedRevision,
	)
	var i CampaignDocument
	err := row.Scan(
		&i.CampaignID,
		&i.Body,
		&i.Revision,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertTableRules = `-- name: UpsertTableRules :one
INSERT INTO campaign_table_rules (
    campaign_id, hit_points_rule, ability_standard_array, ability_point_buy, ability_roll_4d6, ability_typed,
    critical_rule, death_saves, combat_starts_with_map, fog_on_new_maps, house_rules, updated_at
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11::TEXT[], $12
)
ON CONFLICT (campaign_id) DO UPDATE SET
    hit_points_rule = excluded.hit_points_rule,
    ability_standard_array = excluded.ability_standard_array,
    ability_point_buy = excluded.ability_point_buy,
    ability_roll_4d6 = excluded.ability_roll_4d6,
    ability_typed = excluded.ability_typed,
    critical_rule = excluded.critical_rule,
    death_saves = excluded.death_saves,
    combat_starts_with_map = excluded.combat_starts_with_map,
    fog_on_new_maps = excluded.fog_on_new_maps,
    house_rules = excluded.house_rules,
    updated_at = excluded.updated_at
RETURNING campaign_id, hit_points_rule, ability_standard_array, ability_point_buy, ability_roll_4d6, ability_typed, critical_rule, death_saves, combat_starts_with_map, fog_on_new_maps, house_rules, updated_at
`

type UpsertTableRulesParams struct {
	CampaignID           string
	HitPointsRule        string
	AbilityStandardArray bool
	AbilityPointBuy      bool
	AbilityRoll4d6       bool
	AbilityTyped         bool
	CriticalRule         string
	DeathSaves           string
	CombatStartsWithMap  bool
	FogOnNewMaps         bool
	HouseRules           []string
	Now                  time.Time
}

// The master saved "Regras da mesa": every setting is written.
func (q *Queries) UpsertTableRules(ctx context.Context, arg UpsertTableRulesParams) (CampaignTableRule, error) {
	row := q.db.QueryRow(ctx, upsertTableRules,
		arg.CampaignID,
		arg.HitPointsRule,
		arg.AbilityStandardArray,
		arg.AbilityPointBuy,
		arg.AbilityRoll4d6,
		arg.AbilityTyped,
		arg.CriticalRule,
		arg.DeathSaves,
		arg.CombatStartsWithMap,
		arg.FogOnNewMaps,
		arg.HouseRules,
		arg.Now,
	)
	var i CampaignTableRule
	err := row.Scan(
		&i.CampaignID,
		&i.HitPointsRule,
		&i.AbilityStandardArray,
		&i.AbilityPointBuy,
		&i.AbilityRoll4d6,
		&i.AbilityTyped,
		&i.CriticalRule,
		&i.DeathSaves,
		&i.CombatStartsWithMap,
		&i.FogOnNewMaps,
		&i.HouseRules,
		&i.UpdatedAt,
	)
	return i, err
}
