// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package identitydb

import (
	"context"
	"time"
)

const countOtherSessions = `-- name: CountOtherSessions :one
SELECT count(*) FROM auth_sessions
WHERE user_id = $1 AND id <> $2
  AND expires_at > $3 AND last_used_at > $4
`

type CountOtherSessionsParams struct {
	UserID    string
	KeepID    string
	Now       time.Time
	IdleSince time.Time
}

// The user's other sessions that still work.
func (q *Queries) CountOtherSessions(ctx context.Context, arg CountOtherSessionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOtherSessions,
		arg.UserID,
		arg.KeepID,
		arg.Now,
		arg.IdleSince,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOtherUserSessions = `-- name: DeleteOtherUserSessions :execrows
DELETE FROM auth_sessions
WHERE user_id = $1 AND id <> $2
  AND expires_at > $3
`

type DeleteOtherUserSessionsParams struct {
	UserID string
	KeepID string
	Now    time.Time
}

// "Sign out of other devices": every session of the user that has not expired,
// but the current one. Idle rows go too: an idle row is only unusable under
// today's idle timeout, and a longer one would make it valid again.
func (q *Queries) DeleteOtherUserSessions(ctx context.Context, arg DeleteOtherUserSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOtherUserSessions, arg.UserID, arg.KeepID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM auth_sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM auth_sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getDisplayName = `-- name: GetDisplayName :one
SELECT display_name FROM users WHERE id = $1
`

func (q *Queries) GetDisplayName(ctx context.Context, id string) (*string, error) {
	row := q.db.QueryRow(ctx, getDisplayName, id)
	var display_name *string
	err := row.Scan(&display_name)
	return display_name, err
}

const insertIdentity = `-- name: InsertIdentity :exec
INSERT INTO user_identities (issuer, subject, user_id, email)
VALUES ($1, $2, $3, $4)
`

type InsertIdentityParams struct {
	Issuer  string
	Subject string
	UserID  string
	Email   *string
}

func (q *Queries) InsertIdentity(ctx context.Context, arg InsertIdentityParams) error {
	_, err := q.db.Exec(ctx, insertIdentity,
		arg.Issuer,
		arg.Subject,
		arg.UserID,
		arg.Email,
	)
	return err
}

const insertLoginState = `-- name: InsertLoginState :exec
INSERT INTO oidc_login_states
    (state_hash, code_verifier, nonce, return_to, created_at, expires_at, intent_kind, intent_data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertLoginStateParams struct {
	StateHash    []byte
	CodeVerifier string
	Nonce        string
	ReturnTo     string
	CreatedAt    time.Time
	ExpiresAt    time.Time
	IntentKind   *string
	IntentData   []byte
}

func (q *Queries) InsertLoginState(ctx context.Context, arg InsertLoginStateParams) error {
	_, err := q.db.Exec(ctx, insertLoginState,
		arg.StateHash,
		arg.CodeVerifier,
		arg.Nonce,
		arg.ReturnTo,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.IntentKind,
		arg.IntentData,
	)
	return err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO auth_sessions (token_hash, user_id, created_at, expires_at, auth_time, last_used_at)
VALUES ($1, $2, $3, $4, $5, $3)
RETURNING id
`

type InsertSessionParams struct {
	TokenHash []byte
	UserID    string
	CreatedAt time.Time
	ExpiresAt time.Time
	AuthTime  *time.Time
}

// A new session counts as used at the moment it starts.
func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (string, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.TokenHash,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.AuthTime,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users DEFAULT VALUES RETURNING id
`

func (q *Queries) InsertUser(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, insertUser)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listDisplayNames = `-- name: ListDisplayNames :many
SELECT id, display_name::TEXT AS display_name
FROM users
WHERE id = ANY($1::UUID[]) AND display_name IS NOT NULL
`

type ListDisplayNamesRow struct {
	ID          string
	DisplayName string
}

// Users without a display name are left out.
func (q *Queries) ListDisplayNames(ctx context.Context, ids []string) ([]ListDisplayNamesRow, error) {
	rows, err := q.db.Query(ctx, listDisplayNames, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDisplayNamesRow
	for rows.Next() {
		var i ListDisplayNamesRow
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedEmails = `-- name: ListVerifiedEmails :many
SELECT email::TEXT AS email
FROM user_identities
WHERE user_id = $1 AND email IS NOT NULL
`

// The e-mails the provider vouched for (an unverified one is never stored).
// campaigns reads them for the allow-list of who may create campaigns (RN-30).
func (q *Queries) ListVerifiedEmails(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listVerifiedEmails, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupSession = `-- name: LookupSession :one
SELECT id, user_id, created_at, expires_at, last_used_at
FROM auth_sessions
WHERE token_hash = $1 AND expires_at > $2 AND last_used_at > $3
`

type LookupSessionParams struct {
	TokenHash []byte
	Now       time.Time
	IdleSince time.Time
}

type LookupSessionRow struct {
	ID         string
	UserID     string
	CreatedAt  time.Time
	ExpiresAt  time.Time
	LastUsedAt time.Time
}

// A session ends at expires_at (30 days), or when it has not been used since
// idle_since (now minus the idle timeout). Either way it looks like a missing
// one. last_used_at is not in the covering index, so this reads the row.
func (q *Queries) LookupSession(ctx context.Context, arg LookupSessionParams) (LookupSessionRow, error) {
	row := q.db.QueryRow(ctx, lookupSession, arg.TokenHash, arg.Now, arg.IdleSince)
	var i LookupSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const sessionIsActive = `-- name: SessionIsActive :one
SELECT EXISTS (
    SELECT 1 FROM auth_sessions
    WHERE id = $1 AND expires_at > $2 AND last_used_at > $3
)
`

type SessionIsActiveParams struct {
	ID        string
	Now       time.Time
	IdleSince time.Time
}

// A long-lived stream checks its session again by ID (RecheckSession): it
// is still there (no sign-out, no revocation), has not expired and is not idle.
func (q *Queries) SessionIsActive(ctx context.Context, arg SessionIsActiveParams) (bool, error) {
	row := q.db.QueryRow(ctx, sessionIsActive, arg.ID, arg.Now, arg.IdleSince)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setDisplayName = `-- name: SetDisplayName :execrows
UPDATE users SET display_name = $2 WHERE id = $1
`

type SetDisplayNameParams struct {
	ID          string
	DisplayName *string
}

func (q *Queries) SetDisplayName(ctx context.Context, arg SetDisplayNameParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDisplayName, arg.ID, arg.DisplayName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const takeLoginState = `-- name: TakeLoginState :one
DELETE FROM oidc_login_states
WHERE state_hash = $1
RETURNING code_verifier, nonce, return_to, created_at, expires_at, intent_kind, intent_data
`

type TakeLoginStateRow struct {
	CodeVerifier string
	Nonce        string
	ReturnTo     string
	CreatedAt    time.Time
	ExpiresAt    time.Time
	IntentKind   *string
	IntentData   []byte
}

// Reads and deletes in one statement, so two callbacks racing with the same
// state cannot both get it.
func (q *Queries) TakeLoginState(ctx context.Context, stateHash []byte) (TakeLoginStateRow, error) {
	row := q.db.QueryRow(ctx, takeLoginState, stateHash)
	var i TakeLoginStateRow
	err := row.Scan(
		&i.CodeVerifier,
		&i.Nonce,
		&i.ReturnTo,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IntentKind,
		&i.IntentData,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :execrows
UPDATE auth_sessions SET last_used_at = $2
WHERE id = $1 AND last_used_at < $3
`

type TouchSessionParams struct {
	ID          string
	Now         time.Time
	StaleBefore time.Time
}

// One conditional UPDATE: it writes only when the stored time is older than
// stale_before, so the callers can try on every request and a busy session
// still costs about one write per throttle window. A race between two
// instances just writes twice.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchSession, arg.ID, arg.Now, arg.StaleBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateIdentityEmail = `-- name: UpdateIdentityEmail :one
UPDATE user_identities SET email = $3
WHERE issuer = $1 AND subject = $2
RETURNING user_id
`

type UpdateIdentityEmailParams struct {
	Issuer  string
	Subject string
	Email   *string
}

func (q *Queries) UpdateIdentityEmail(ctx context.Context, arg UpdateIdentityEmailParams) (string, error) {
	row := q.db.QueryRow(ctx, updateIdentityEmail, arg.Issuer, arg.Subject, arg.Email)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}
