// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package progressiondb

import (
	"time"
)

type PlannedMilestone struct {
	ID         string
	CampaignID string
	Position   int32
	Text       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	CreateKey  *string
	CreateHash *string
}

type XpAward struct {
	ID              string
	CampaignID      string
	GivenBy         *string
	CreatedAt       time.Time
	Mode            string
	Reason          string
	EncounterID     *string
	Gold            *int32
	TotalXp         int32
	IdempotencyKey  string
	UndoneAt        *time.Time
	UndoneBy        *string
	UndoKey         *string
	MilestoneID     *string
	MilestoneAgain  bool
	IdempotencyHash *string
}

type XpAwardShare struct {
	AwardID     string
	CharacterID string
	Xp          int32
	LevelAtMark *int32
}

type XpAwardTreasure struct {
	AwardID string
	PointID string
	ValuePo int32
}
