// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package progressiondb

import (
	"context"
	"time"
)

const deletePlannedMilestone = `-- name: DeletePlannedMilestone :exec
DELETE FROM planned_milestones
WHERE campaign_id = $1::UUID AND id = $2::UUID
`

type DeletePlannedMilestoneParams struct {
	CampaignID string
	ID         string
}

func (q *Queries) DeletePlannedMilestone(ctx context.Context, arg DeletePlannedMilestoneParams) error {
	_, err := q.db.Exec(ctx, deletePlannedMilestone, arg.CampaignID, arg.ID)
	return err
}

const getLastXPAwardForUpdate = `-- name: GetLastXPAwardForUpdate :one
SELECT id, campaign_id, given_by, created_at, mode, reason, encounter_id, gold, total_xp, idempotency_key, undone_at, undone_by, undo_key, milestone_id, milestone_again, idempotency_hash FROM xp_awards
WHERE campaign_id = $1::UUID AND undone_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT 1
FOR UPDATE
`

// The award an undo would take back: the newest one not undone. FOR UPDATE, so
// two undos wait for each other instead of both taking back the same award.
func (q *Queries) GetLastXPAwardForUpdate(ctx context.Context, campaignID string) (XpAward, error) {
	row := q.db.QueryRow(ctx, getLastXPAwardForUpdate, campaignID)
	var i XpAward
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.GivenBy,
		&i.CreatedAt,
		&i.Mode,
		&i.Reason,
		&i.EncounterID,
		&i.Gold,
		&i.TotalXp,
		&i.IdempotencyKey,
		&i.UndoneAt,
		&i.UndoneBy,
		&i.UndoKey,
		&i.MilestoneID,
		&i.MilestoneAgain,
		&i.IdempotencyHash,
	)
	return i, err
}

const getLastXPAwardID = `-- name: GetLastXPAwardID :one
SELECT id FROM xp_awards
WHERE campaign_id = $1::UUID AND undone_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// The newest award not undone, for the history's "Desfazer".
func (q *Queries) GetLastXPAwardID(ctx context.Context, campaignID string) (string, error) {
	row := q.db.QueryRow(ctx, getLastXPAwardID, campaignID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getMilestoneMark = `-- name: GetMilestoneMark :one
SELECT COALESCE(max(s.level_at_mark), 0)::INT4 AS level
FROM xp_award_shares AS s
JOIN xp_awards AS a ON a.id = s.award_id
WHERE a.campaign_id = $1::UUID AND a.mode = 'milestone' AND a.undone_at IS NULL
  AND s.character_id = $2::UUID AND s.level_at_mark IS NOT NULL
`

type GetMilestoneMarkParams struct {
	CampaignID  string
	CharacterID string
}

// ListMilestoneMarks for one character; no row means it is not marked.
func (q *Queries) GetMilestoneMark(ctx context.Context, arg GetMilestoneMarkParams) (int32, error) {
	row := q.db.QueryRow(ctx, getMilestoneMark, arg.CampaignID, arg.CharacterID)
	var level int32
	err := row.Scan(&level)
	return level, err
}

const getPlannedMilestoneByCreateKey = `-- name: GetPlannedMilestoneByCreateKey :one
SELECT id, campaign_id, position, text, created_at, updated_at, create_key, create_hash FROM planned_milestones WHERE create_key = $1
`

// The milestone an AddMilestone with this idempotency key made, if any (the key carries the
// campaign's ID).
func (q *Queries) GetPlannedMilestoneByCreateKey(ctx context.Context, createKey *string) (PlannedMilestone, error) {
	row := q.db.QueryRow(ctx, getPlannedMilestoneByCreateKey, createKey)
	var i PlannedMilestone
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Position,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreateKey,
		&i.CreateHash,
	)
	return i, err
}

const getPlannedMilestoneForUpdate = `-- name: GetPlannedMilestoneForUpdate :one
SELECT id, campaign_id, position, text, created_at, updated_at, create_key, create_hash FROM planned_milestones
WHERE campaign_id = $1::UUID AND id = $2::UUID
FOR UPDATE
`

type GetPlannedMilestoneForUpdateParams struct {
	CampaignID string
	ID         string
}

func (q *Queries) GetPlannedMilestoneForUpdate(ctx context.Context, arg GetPlannedMilestoneForUpdateParams) (PlannedMilestone, error) {
	row := q.db.QueryRow(ctx, getPlannedMilestoneForUpdate, arg.CampaignID, arg.ID)
	var i PlannedMilestone
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Position,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreateKey,
		&i.CreateHash,
	)
	return i, err
}

const getXPAwardByKey = `-- name: GetXPAwardByKey :one
SELECT id, campaign_id, given_by, created_at, mode, reason, encounter_id, gold, total_xp, idempotency_key, undone_at, undone_by, undo_key, milestone_id, milestone_again, idempotency_hash FROM xp_awards
WHERE campaign_id = $1::UUID AND idempotency_key = $2::UUID
`

type GetXPAwardByKeyParams struct {
	CampaignID     string
	IdempotencyKey string
}

// The award a retry of the same request finds.
func (q *Queries) GetXPAwardByKey(ctx context.Context, arg GetXPAwardByKeyParams) (XpAward, error) {
	row := q.db.QueryRow(ctx, getXPAwardByKey, arg.CampaignID, arg.IdempotencyKey)
	var i XpAward
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.GivenBy,
		&i.CreatedAt,
		&i.Mode,
		&i.Reason,
		&i.EncounterID,
		&i.Gold,
		&i.TotalXp,
		&i.IdempotencyKey,
		&i.UndoneAt,
		&i.UndoneBy,
		&i.UndoKey,
		&i.MilestoneID,
		&i.MilestoneAgain,
		&i.IdempotencyHash,
	)
	return i, err
}

const getXPAwardByUndoKey = `-- name: GetXPAwardByUndoKey :one
SELECT id, campaign_id, given_by, created_at, mode, reason, encounter_id, gold, total_xp, idempotency_key, undone_at, undone_by, undo_key, milestone_id, milestone_again, idempotency_hash FROM xp_awards
WHERE campaign_id = $1::UUID AND undo_key = $2::UUID
`

type GetXPAwardByUndoKeyParams struct {
	CampaignID string
	UndoKey    string
}

// The award a retry of the same undo finds.
func (q *Queries) GetXPAwardByUndoKey(ctx context.Context, arg GetXPAwardByUndoKeyParams) (XpAward, error) {
	row := q.db.QueryRow(ctx, getXPAwardByUndoKey, arg.CampaignID, arg.UndoKey)
	var i XpAward
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.GivenBy,
		&i.CreatedAt,
		&i.Mode,
		&i.Reason,
		&i.EncounterID,
		&i.Gold,
		&i.TotalXp,
		&i.IdempotencyKey,
		&i.UndoneAt,
		&i.UndoneBy,
		&i.UndoKey,
		&i.MilestoneID,
		&i.MilestoneAgain,
		&i.IdempotencyHash,
	)
	return i, err
}

const hasLiveEnemiesAward = `-- name: HasLiveEnemiesAward :one
SELECT EXISTS (
    SELECT 1 FROM xp_awards
    WHERE campaign_id = $1::UUID AND encounter_id = $2::UUID
      AND mode = 'enemies' AND undone_at IS NULL
)
`

type HasLiveEnemiesAwardParams struct {
	CampaignID  string
	EncounterID string
}

// Whether the combat's XP was already given (and not undone).
func (q *Queries) HasLiveEnemiesAward(ctx context.Context, arg HasLiveEnemiesAwardParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasLiveEnemiesAward, arg.CampaignID, arg.EncounterID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasMilestoneAwards = `-- name: HasMilestoneAwards :one
SELECT EXISTS (
    SELECT 1 FROM xp_awards
    WHERE campaign_id = $1::UUID AND milestone_id = $2::UUID
)
`

type HasMilestoneAwardsParams struct {
	CampaignID  string
	MilestoneID string
}

// Whether any award, undone ones included, names the milestone: a milestone
// with history is never removed (ADR-0007: awards are never rewritten).
func (q *Queries) HasMilestoneAwards(ctx context.Context, arg HasMilestoneAwardsParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasMilestoneAwards, arg.CampaignID, arg.MilestoneID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertPlannedMilestone = `-- name: InsertPlannedMilestone :one
INSERT INTO planned_milestones (campaign_id, position, text, create_key, create_hash, created_at, updated_at)
VALUES ($1::UUID, $2, $3, $4, $5, $6, $6)
ON CONFLICT (create_key) WHERE create_key IS NOT NULL DO NOTHING
RETURNING id, campaign_id, position, text, created_at, updated_at, create_key, create_hash
`

type InsertPlannedMilestoneParams struct {
	CampaignID string
	Position   int32
	Text       string
	CreateKey  *string
	CreateHash *string
	Now        time.Time
}

// create_key and create_hash are the idempotency key and the hash of the request (NULL when the
// call sent no key); the caller reads the first row with GetPlannedMilestoneByCreateKey.
func (q *Queries) InsertPlannedMilestone(ctx context.Context, arg InsertPlannedMilestoneParams) (PlannedMilestone, error) {
	row := q.db.QueryRow(ctx, insertPlannedMilestone,
		arg.CampaignID,
		arg.Position,
		arg.Text,
		arg.CreateKey,
		arg.CreateHash,
		arg.Now,
	)
	var i PlannedMilestone
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Position,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreateKey,
		&i.CreateHash,
	)
	return i, err
}

const insertXPAward = `-- name: InsertXPAward :one

INSERT INTO xp_awards
    (campaign_id, given_by, created_at, mode, reason, encounter_id, gold, total_xp, idempotency_key, milestone_id, milestone_again, idempotency_hash)
VALUES (
    $1::UUID, $2::UUID, $3, $4, $5,
    $6::UUID, $7, $8, $9::UUID,
    $10::UUID, $11::BOOL, $12
)
RETURNING id, campaign_id, given_by, created_at, mode, reason, encounter_id, gold, total_xp, idempotency_key, undone_at, undone_by, undo_key, milestone_id, milestone_again, idempotency_hash
`

type InsertXPAwardParams struct {
	CampaignID      string
	GivenBy         string
	CreatedAt       time.Time
	Mode            string
	Reason          string
	EncounterID     *string
	Gold            *int32
	TotalXp         int32
	IdempotencyKey  string
	MilestoneID     *string
	MilestoneAgain  bool
	IdempotencyHash *string
}

// Every query names the campaign next to the award: an award ID of another
// campaign matches no row.
func (q *Queries) InsertXPAward(ctx context.Context, arg InsertXPAwardParams) (XpAward, error) {
	row := q.db.QueryRow(ctx, insertXPAward,
		arg.CampaignID,
		arg.GivenBy,
		arg.CreatedAt,
		arg.Mode,
		arg.Reason,
		arg.EncounterID,
		arg.Gold,
		arg.TotalXp,
		arg.IdempotencyKey,
		arg.MilestoneID,
		arg.MilestoneAgain,
		arg.IdempotencyHash,
	)
	var i XpAward
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.GivenBy,
		&i.CreatedAt,
		&i.Mode,
		&i.Reason,
		&i.EncounterID,
		&i.Gold,
		&i.TotalXp,
		&i.IdempotencyKey,
		&i.UndoneAt,
		&i.UndoneBy,
		&i.UndoKey,
		&i.MilestoneID,
		&i.MilestoneAgain,
		&i.IdempotencyHash,
	)
	return i, err
}

const insertXPAwardTreasure = `-- name: InsertXPAwardTreasure :exec

INSERT INTO xp_award_treasures (award_id, point_id, value_po)
VALUES ($1::UUID, $2::UUID, $3)
`

type InsertXPAwardTreasureParams struct {
	AwardID string
	PointID string
	ValuePo int32
}

// The treasures a "Voltar à cidade" award converted (00101).
func (q *Queries) InsertXPAwardTreasure(ctx context.Context, arg InsertXPAwardTreasureParams) error {
	_, err := q.db.Exec(ctx, insertXPAwardTreasure, arg.AwardID, arg.PointID, arg.ValuePo)
	return err
}

const insertXPShare = `-- name: InsertXPShare :exec
INSERT INTO xp_award_shares (award_id, character_id, xp, level_at_mark)
VALUES ($1::UUID, $2::UUID, $3, $4)
`

type InsertXPShareParams struct {
	AwardID     string
	CharacterID string
	Xp          int32
	LevelAtMark *int32
}

func (q *Queries) InsertXPShare(ctx context.Context, arg InsertXPShareParams) error {
	_, err := q.db.Exec(ctx, insertXPShare,
		arg.AwardID,
		arg.CharacterID,
		arg.Xp,
		arg.LevelAtMark,
	)
	return err
}

const listLiveMilestoneAwards = `-- name: ListLiveMilestoneAwards :many
SELECT id, campaign_id, given_by, created_at, mode, reason, encounter_id, gold, total_xp, idempotency_key, undone_at, undone_by, undo_key, milestone_id, milestone_again, idempotency_hash FROM xp_awards
WHERE campaign_id = $1::UUID AND mode = 'milestone' AND undone_at IS NULL
ORDER BY created_at, id
`

// The milestone marks that are not undone, oldest first: those of the planned
// milestones (what makes one reached) and the ones marked off the list
// (milestone_id NULL).
func (q *Queries) ListLiveMilestoneAwards(ctx context.Context, campaignID string) ([]XpAward, error) {
	rows, err := q.db.Query(ctx, listLiveMilestoneAwards, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []XpAward
	for rows.Next() {
		var i XpAward
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.GivenBy,
			&i.CreatedAt,
			&i.Mode,
			&i.Reason,
			&i.EncounterID,
			&i.Gold,
			&i.TotalXp,
			&i.IdempotencyKey,
			&i.UndoneAt,
			&i.UndoneBy,
			&i.UndoKey,
			&i.MilestoneID,
			&i.MilestoneAgain,
			&i.IdempotencyHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveMilestoneAwardsOf = `-- name: ListLiveMilestoneAwardsOf :many
SELECT id, campaign_id, given_by, created_at, mode, reason, encounter_id, gold, total_xp, idempotency_key, undone_at, undone_by, undo_key, milestone_id, milestone_again, idempotency_hash FROM xp_awards
WHERE campaign_id = $1::UUID AND milestone_id = $2::UUID AND undone_at IS NULL
ORDER BY created_at, id
`

type ListLiveMilestoneAwardsOfParams struct {
	CampaignID  string
	MilestoneID string
}

// The same for one milestone.
func (q *Queries) ListLiveMilestoneAwardsOf(ctx context.Context, arg ListLiveMilestoneAwardsOfParams) ([]XpAward, error) {
	rows, err := q.db.Query(ctx, listLiveMilestoneAwardsOf, arg.CampaignID, arg.MilestoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []XpAward
	for rows.Next() {
		var i XpAward
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.GivenBy,
			&i.CreatedAt,
			&i.Mode,
			&i.Reason,
			&i.EncounterID,
			&i.Gold,
			&i.TotalXp,
			&i.IdempotencyKey,
			&i.UndoneAt,
			&i.UndoneBy,
			&i.UndoKey,
			&i.MilestoneID,
			&i.MilestoneAgain,
			&i.IdempotencyHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMilestoneIDsWithAwards = `-- name: ListMilestoneIDsWithAwards :many
SELECT DISTINCT milestone_id::UUID AS milestone_id FROM xp_awards
WHERE campaign_id = $1::UUID AND milestone_id IS NOT NULL
`

// The planned milestones any award names, undone ones included: HasMilestoneAwards
// for the whole list, so the list can say which ones RemoveMilestone refuses.
func (q *Queries) ListMilestoneIDsWithAwards(ctx context.Context, campaignID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listMilestoneIDsWithAwards, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var milestone_id string
		if err := rows.Scan(&milestone_id); err != nil {
			return nil, err
		}
		items = append(items, milestone_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMilestoneMarkedCharacters = `-- name: ListMilestoneMarkedCharacters :many
SELECT s.character_id
FROM xp_award_shares AS s
JOIN xp_awards AS a ON a.id = s.award_id
WHERE a.campaign_id = $1::UUID AND a.milestone_id = $2::UUID AND a.undone_at IS NULL
`

type ListMilestoneMarkedCharactersParams struct {
	CampaignID  string
	MilestoneID string
}

// The characters that have the milestone now (a mark not undone).
func (q *Queries) ListMilestoneMarkedCharacters(ctx context.Context, arg ListMilestoneMarkedCharactersParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listMilestoneMarkedCharacters, arg.CampaignID, arg.MilestoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var character_id string
		if err := rows.Scan(&character_id); err != nil {
			return nil, err
		}
		items = append(items, character_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMilestoneMarks = `-- name: ListMilestoneMarks :many
SELECT s.character_id, max(s.level_at_mark)::INT4 AS level
FROM xp_award_shares AS s
JOIN xp_awards AS a ON a.id = s.award_id
WHERE a.campaign_id = $1::UUID AND a.mode = 'milestone' AND a.undone_at IS NULL
  AND s.level_at_mark IS NOT NULL
GROUP BY s.character_id
`

type ListMilestoneMarksRow struct {
	CharacterID string
	Level       int32
}

// The highest level each character of the campaign was marked at, by the
// milestones not undone: the "pode subir de nível" tag lasts until the sheet's
// level goes past it (RN-12).
func (q *Queries) ListMilestoneMarks(ctx context.Context, campaignID string) ([]ListMilestoneMarksRow, error) {
	rows, err := q.db.Query(ctx, listMilestoneMarks, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMilestoneMarksRow
	for rows.Next() {
		var i ListMilestoneMarksRow
		if err := rows.Scan(&i.CharacterID, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlannedMilestones = `-- name: ListPlannedMilestones :many

SELECT id, campaign_id, position, text, created_at, updated_at, create_key, create_hash FROM planned_milestones
WHERE campaign_id = $1::UUID
ORDER BY position, id
`

// The planned milestones (00084). Every query names the campaign next to the
// milestone: an ID of another campaign matches no row.
func (q *Queries) ListPlannedMilestones(ctx context.Context, campaignID string) ([]PlannedMilestone, error) {
	rows, err := q.db.Query(ctx, listPlannedMilestones, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlannedMilestone
	for rows.Next() {
		var i PlannedMilestone
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Position,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreateKey,
			&i.CreateHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlannedMilestonesForUpdate = `-- name: ListPlannedMilestonesForUpdate :many
SELECT id, campaign_id, position, text, created_at, updated_at, create_key, create_hash FROM planned_milestones
WHERE campaign_id = $1::UUID
ORDER BY position, id
FOR UPDATE
`

// The campaign's whole list, locked: an add or a move takes turns with the
// others, so positions never repeat and the count limit holds.
func (q *Queries) ListPlannedMilestonesForUpdate(ctx context.Context, campaignID string) ([]PlannedMilestone, error) {
	rows, err := q.db.Query(ctx, listPlannedMilestonesForUpdate, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlannedMilestone
	for rows.Next() {
		var i PlannedMilestone
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Position,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreateKey,
			&i.CreateHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listXPAwardTreasures = `-- name: ListXPAwardTreasures :many
SELECT award_id, point_id, value_po
FROM xp_award_treasures
WHERE award_id = ANY($1::UUID[])
ORDER BY award_id, point_id
`

func (q *Queries) ListXPAwardTreasures(ctx context.Context, awardIds []string) ([]XpAwardTreasure, error) {
	rows, err := q.db.Query(ctx, listXPAwardTreasures, awardIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []XpAwardTreasure
	for rows.Next() {
		var i XpAwardTreasure
		if err := rows.Scan(&i.AwardID, &i.PointID, &i.ValuePo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listXPAwardsPage = `-- name: ListXPAwardsPage :many
SELECT id, campaign_id, given_by, created_at, mode, reason, encounter_id, gold, total_xp, idempotency_key, undone_at, undone_by, undo_key, milestone_id, milestone_again, idempotency_hash FROM xp_awards
WHERE campaign_id = $1::UUID
  AND (
      $2::TIMESTAMPTZ IS NULL
      OR (created_at, id) < ($2::TIMESTAMPTZ, $3::UUID)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListXPAwardsPageParams struct {
	CampaignID      string
	BeforeCreatedAt *time.Time
	BeforeID        *string
	PageSize        int32
}

// A page of the history, newest first: the awards before the cursor (created_at
// and id of the last one of the previous page), or the first page without it.
func (q *Queries) ListXPAwardsPage(ctx context.Context, arg ListXPAwardsPageParams) ([]XpAward, error) {
	rows, err := q.db.Query(ctx, listXPAwardsPage,
		arg.CampaignID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []XpAward
	for rows.Next() {
		var i XpAward
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.GivenBy,
			&i.CreatedAt,
			&i.Mode,
			&i.Reason,
			&i.EncounterID,
			&i.Gold,
			&i.TotalXp,
			&i.IdempotencyKey,
			&i.UndoneAt,
			&i.UndoneBy,
			&i.UndoKey,
			&i.MilestoneID,
			&i.MilestoneAgain,
			&i.IdempotencyHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listXPSharesOfAwards = `-- name: ListXPSharesOfAwards :many
SELECT s.award_id, s.character_id, s.xp, s.level_at_mark
FROM xp_award_shares AS s
JOIN characters AS c ON c.id = s.character_id
WHERE s.award_id = ANY($1::UUID[])
ORDER BY c.created_at, c.id
`

func (q *Queries) ListXPSharesOfAwards(ctx context.Context, awardIds []string) ([]XpAwardShare, error) {
	rows, err := q.db.Query(ctx, listXPSharesOfAwards, awardIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []XpAwardShare
	for rows.Next() {
		var i XpAwardShare
		if err := rows.Scan(
			&i.AwardID,
			&i.CharacterID,
			&i.Xp,
			&i.LevelAtMark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markXPAwardUndone = `-- name: MarkXPAwardUndone :one
UPDATE xp_awards
SET undone_at = $1, undone_by = $2::UUID, undo_key = $3::UUID
WHERE campaign_id = $4::UUID AND id = $5::UUID AND undone_at IS NULL
RETURNING id, campaign_id, given_by, created_at, mode, reason, encounter_id, gold, total_xp, idempotency_key, undone_at, undone_by, undo_key, milestone_id, milestone_again, idempotency_hash
`

type MarkXPAwardUndoneParams struct {
	UndoneAt   *time.Time
	UndoneBy   string
	UndoKey    string
	CampaignID string
	ID         string
}

// undone_at IS NULL in the WHERE clause is a second guard: no row means it was
// undone meanwhile.
func (q *Queries) MarkXPAwardUndone(ctx context.Context, arg MarkXPAwardUndoneParams) (XpAward, error) {
	row := q.db.QueryRow(ctx, markXPAwardUndone,
		arg.UndoneAt,
		arg.UndoneBy,
		arg.UndoKey,
		arg.CampaignID,
		arg.ID,
	)
	var i XpAward
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.GivenBy,
		&i.CreatedAt,
		&i.Mode,
		&i.Reason,
		&i.EncounterID,
		&i.Gold,
		&i.TotalXp,
		&i.IdempotencyKey,
		&i.UndoneAt,
		&i.UndoneBy,
		&i.UndoKey,
		&i.MilestoneID,
		&i.MilestoneAgain,
		&i.IdempotencyHash,
	)
	return i, err
}

const setPlannedMilestonePosition = `-- name: SetPlannedMilestonePosition :exec
UPDATE planned_milestones SET position = $1
WHERE campaign_id = $2::UUID AND id = $3::UUID
`

type SetPlannedMilestonePositionParams struct {
	Position   int32
	CampaignID string
	ID         string
}

func (q *Queries) SetPlannedMilestonePosition(ctx context.Context, arg SetPlannedMilestonePositionParams) error {
	_, err := q.db.Exec(ctx, setPlannedMilestonePosition, arg.Position, arg.CampaignID, arg.ID)
	return err
}

const sumLiveAwards = `-- name: SumLiveAwards :one
SELECT count(*)::INT4 AS awards,
       COALESCE((SELECT sum(s.xp) FROM xp_award_shares AS s JOIN xp_awards AS a2 ON a2.id = s.award_id
                 WHERE a2.campaign_id = $1::UUID AND a2.undone_at IS NULL), 0)::INT8 AS total_xp
FROM xp_awards
WHERE campaign_id = $1::UUID AND undone_at IS NULL
`

type SumLiveAwardsRow struct {
	Awards  int32
	TotalXp int64
}

// How much XP the campaign gave and has not undone (RN-09): the awards that
// stand (a milestone mark is one, with no XP) and what the characters got from
// them. The master's change of the XP mode asks before it goes on.
func (q *Queries) SumLiveAwards(ctx context.Context, campaignID string) (SumLiveAwardsRow, error) {
	row := q.db.QueryRow(ctx, sumLiveAwards, campaignID)
	var i SumLiveAwardsRow
	err := row.Scan(&i.Awards, &i.TotalXp)
	return i, err
}

const updatePlannedMilestoneText = `-- name: UpdatePlannedMilestoneText :exec
UPDATE planned_milestones SET text = $1, updated_at = $2
WHERE campaign_id = $3::UUID AND id = $4::UUID
`

type UpdatePlannedMilestoneTextParams struct {
	Text       string
	Now        time.Time
	CampaignID string
	ID         string
}

func (q *Queries) UpdatePlannedMilestoneText(ctx context.Context, arg UpdatePlannedMilestoneTextParams) error {
	_, err := q.db.Exec(ctx, updatePlannedMilestoneText,
		arg.Text,
		arg.Now,
		arg.CampaignID,
		arg.ID,
	)
	return err
}
